name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Login to Azure CLI
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ Create Azure Container Registry if not exists
      - name: Create ACR
        run: |
          az acr show --name myregistryaabuabdo --resource-group MyResourceGroup || \
          az acr create --name myregistryaabuabdo --resource-group MyResourceGroup --sku Basic --admin-enabled true

      # 4️⃣ List files in project directory
      - name: List project directory
        run: ls -al ./src/GithubCI.WebApi

      # 5️⃣ Build Docker image locally
      - name: Build Docker image
        run: docker build ./src/GithubCI.WebApi --file ./src/GithubCI.WebApi/Dockerfile --tag my-image-name:test

      # 6️⃣ Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: |
          az acr login --name myregistryaabuabdo

      # 7️⃣ Build and Push Docker image to ACR
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./src/GithubCI.WebApi
          file: ./src/GithubCI.WebApi/Dockerfile
          push: true
          tags: myregistryaabuabdo.azurecr.io/myapp/my-image-name:latest
