name: .NET Build, Test, and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Change if using .NET 6 or 7

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build GithubCI.sln --configuration Release --no-restore

    - name: Run unit tests
      run: dotnet test test/GithubCI.WebApi.Tests/GithubCI.WebApi.Tests.csproj --configuration Release --no-build --verbosity normal

    # 1️⃣ Publish the Web API
    - name: Publish Web API
      run: dotnet publish src/GithubCI.WebApi/GithubCI.WebApi.csproj -c Release -o publish_output

    # 2️⃣ Deploy to Azure Web App
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: YOUR_AZURE_WEBAPP_NAME   # 👈 Replace this with your actual web app name
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: publish_output
