name: Docker CI/CD with Approval

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v4

      # 2️⃣ Login to Azure CLI
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3️⃣ List repo structure (debug)
      - name: Show repo files
        run: ls -R

      # 4️⃣ Create Azure Container Registry if not exists
      - name: Create ACR
        run: |
          az acr show --name myregistryaabuabdo --resource-group az400 || \
          az acr create --name myregistryaabuabdo --resource-group az400 --sku Basic --admin-enabled true

      # 5️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build ${{ github.workspace }}/src/GithubCI.WebApi \
            --file ${{ github.workspace }}/src/GithubCI.WebApi/Dockerfile \
            --tag my-image-name:test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: staging  # ← Approval Gate
    steps:
      # 1️⃣ Login to Azure CLI
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 2️⃣ Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: az acr login --name myregistryaabuabdo

      # 3️⃣ Push Docker image to ACR
      - name: Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ${{ github.workspace }}/src/GithubCI.WebApi
          file: ${{ github.workspace }}/src/GithubCI.WebApi/Dockerfile
          push: true
          tags: myregistryaabuabdo.azurecr.io/myapp/my-image-name:latest
